CREATE DATABASE blog;

--\c into blog database

CREATE TABLE post(
    ID SERIAL UNIQUE NOT NULL,
    TITLE VARCHAR(250) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONTENT_ID INTEGER NOT NULL,
    CATEGORY_ID INTEGER NOT NULL,
    PRIMARY KEY (CONTENT_ID,CATEGORY_ID),
    CONSTRAINT CONTENT_ID FOREIGN KEY (CONTENT_ID)
    REFERENCES CONTENT (CONTENT_ID) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT CATEGORY_ID FOREIGN KEY (CATEGORY_ID)
    REFERENCES CATEGORY (CATEGORY_ID) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION
)


CREATE TABLE category(
    CATEGORY_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(250) UNIQUE NOT NULL
)

CREATE TABLE content(
    CONTENT_ID SERIAL PRIMARY KEY,
    AUTHOR VARCHAR(50) NOT NULL,
    TAG VARCHAR(300) NOT NULL,
    CONTENT_TEXT TEXT NOT NULL, 
    CONTENT_IMG VARCHAR(300) NOT NULL
)