# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: pull 
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: git pull origin 
    
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: | 
            touch .env
            echo "NODE_ENV=${{ secrets.IS_PRODUCTION }}" >> .env
            echo "ACCESS_KEY=${{ secrets.ACCESS_KEY }}" >> .env
            echo "ACCESS_SECRET=${{ secrets.ACCESS_SECRET }}" >> .env
            echo "REGION=${{ secrets.REGION }}" >> .env
            echo "BUCKET=${{ secrets.BUCKET }}" >> .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
            echo "DB_DIALECT=${{ secrets.DB_DIALECT }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_OPERATORS_ALIASES=${{ secrets.DB_OPERATORS_ALIASES }}" >> .env


    - run: npm i
    - run: pm2 restart ecosystem.config.js --env production --name "blog"
    - run: pm2 save
